### ISSUE TITLE
Unused property of the signature and its initialisation

### ISSUE THREAD

**Issue by lbadzaghua** [eBay/digital-signature-java-sdk#3]
Hello, 

 Thank you very much for creating this SDK.  I have some improvements to recommend and wish for.

 In the class [Signature](https://github.com/eBay/digital-signature-java-sdk/blob/73873378c3ff23822d02f13f83938a776c6150c4/src/main/java/com/ebay/developer/Signature.java) it is possible to create a new instance only from a json file, which is not the best approach for production as a file always has to be created, which in turn consumes memory unnecessarily (the same problem with keys, especially with masterKey). So it would be nice to have a constructor with SignatureConfig parameter.

 The second thing is that SignatureConfig is initialised but never used directly in the class. I know how it is used in the example, but that is not the way class properties are supposed to work, as far as I know.

 If you give me permission, I will push branches with changes so you can check them out.

Alternatively see here: [1. Change](https://github.com/eBay/digital-signature-java-sdk/pull/4/commits/47bc7fe19d52f90c20aa4169cdbca39e569ba3a2)

**Comment by evangelosdaniil** [comment]
Any updates on this? As @lbadzaghua mentioned, creating a new instance only from a JSON file is not the best approach as a file always has to be made, which in turn consumes memory unnecessarily

**Comment by dhineshkumars89** [comment]
Thanks @lbadzaghua for PR. I will check and include these changes.
FYI @evangelosdaniil

**Comment by gvastakis** [comment]
hello @dhineshkumars89, are there any updates on this ? Thank you in advance !

**Comment by evangelosdaniil** [comment]
Hello @dhineshkumars89, happy new year! Do you have any updates on this?

**Comment by balintcz** [comment]
Hi @dhineshkumars89, would like an update on this as well because these improvements are really useful

**Comment by dhineshkumars89** [comment]
This improvement was added in 1.1.0-RELEASE version. Thanks @lbadzaghua for PR. 
I'm sorry for the delay in the update.
